name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04  # Specify Ubuntu 22.04 explicitly

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Use a valid version for Ubuntu 22.04

      - name: Debug Python Versions  # Optional: Debug to check available Python versions
        run: ls /opt/hostedtoolcache/Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Linter
        run: |
          pip install --no-cache-dir flake8
          flake8 app.py

      - name: Run Tests
        run: python -m unittest discover -s .
