name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Ensure compatibility
        architecture: x64

    # Install dependencies using Makefile
    - name: Install dependencies
      run: make install

    # Run tests
    - name: Run tests
      run: make test

    # Run linter
    - name: Run linter
      run: make lint

    # Format code
    - name: Format code
      run: make format

    # Clean up temporary files
    - name: Clean up temporary files
      run: make clean

    # Run the application
    - name: Run the application
      run: make run
