name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Change to Windows environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Use a Python version compatible with Windows

      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install flask flake8 black isort unittest

      - name: Run linter
        run: |
          .\venv\Scripts\activate
          flake8 .

      - name: Run tests
        run: |
          .\venv\Scripts\activate
          python -m unittest discover -s . -p "test_*.py"

      - name: Run application
        run: |
          .\venv\Scripts\activate
          python app.py
