name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04  # Explicitly specify Ubuntu version to avoid warnings

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Fetch the latest code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Use a stable Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt  # Force fresh installs

      - name: Run Linter
        run: |
          pip install --no-cache-dir flake8
          flake8 app.py

      - name: Run Tests
        run: python -m unittest discover -s .
